import type { Perspective, Question } from './types'

export const QUESTIONS: Question[] = [
  // ── GOVERNANCE ──────────────────────────────────────────────────────────────
  {
    id: 'G1',
    perspective: 'governance',
    capability: 'Accountability Architecture',
    type: 'anchor',
    weight: 22,
    text: 'Are accountable owners named for AI-supported decisions, and can they be reached when a decision is contested?',
    options: [
      { value: 0, label: 'None' },
      { value: 1, label: 'Informal only' },
      { value: 2, label: 'Some decisions' },
      { value: 3, label: 'Most decisions' },
      { value: 4, label: 'All major decisions, formally assigned' },
      { value: 5, label: 'Continuously measured and enforced' },
    ],
  },
  {
    id: 'G2',
    perspective: 'governance',
    capability: 'Escalation & Exception Handling',
    type: 'anchor',
    weight: 18,
    text: 'When an AI output is disputed or uncertain, what happens operationally? Walk through the last example.',
    options: [
      { value: 0, label: 'No process exists' },
      { value: 1, label: 'Depends on who notices' },
      { value: 2, label: 'Informal escalation sometimes' },
      { value: 3, label: 'Defined path exists, used inconsistently' },
      { value: 4, label: 'Standard process, measured' },
      { value: 5, label: 'Adaptive and continuously improved' },
    ],
  },
  {
    id: 'G3',
    perspective: 'governance',
    capability: 'Human Oversight & Intervention',
    type: 'core',
    weight: 15,
    text: 'Can human reviewers override or pause an AI-supported decision? Show the last time this happened.',
    options: [
      { value: 0, label: 'No override capability' },
      { value: 1, label: 'In principle but no examples' },
      { value: 2, label: 'Occasionally, informally' },
      { value: 3, label: 'Defined authority, used in some workflows' },
      { value: 4, label: 'Formal authority, measured' },
      { value: 5, label: 'Continuously calibrated' },
    ],
  },
  {
    id: 'G4',
    perspective: 'governance',
    capability: 'Runtime Governance & Monitoring',
    type: 'core',
    weight: 14,
    text: 'Does governance monitoring continue after AI systems are deployed? What signals reach governance owners from production?',
    options: [
      { value: 0, label: 'Governance ends at deployment' },
      { value: 1, label: 'Ad hoc monitoring' },
      { value: 2, label: 'Some production signals' },
      { value: 3, label: 'Selected systems monitored' },
      { value: 4, label: 'All production systems, standardized' },
      { value: 5, label: 'Adaptive, predictive' },
    ],
  },
  {
    id: 'G5',
    perspective: 'governance',
    capability: 'Risk Classification & Control',
    type: 'core',
    weight: 12,
    text: 'Are AI use cases classified by risk level, and do higher-risk cases receive more intensive controls?',
    options: [
      { value: 0, label: 'All treated the same' },
      { value: 1, label: 'Informal risk awareness' },
      { value: 2, label: 'Some cases risk-ranked' },
      { value: 3, label: 'Local risk tiers exist' },
      { value: 4, label: 'Enterprise risk classification standard' },
      { value: 5, label: 'Continuously refined' },
    ],
  },
  {
    id: 'G6',
    perspective: 'governance',
    capability: 'Incident & Failure Response',
    type: 'supporting',
    weight: 8,
    text: 'Describe the last AI-related incident: how it was detected, who was notified, what changed as a result.',
    options: [
      { value: 0, label: 'No incidents recognized' },
      { value: 1, label: 'Incidents handled informally' },
      { value: 2, label: 'Some incidents documented' },
      { value: 3, label: 'Classification and escalation process' },
      { value: 4, label: 'Standard process, measured' },
      { value: 5, label: 'Incidents drive systemic improvement' },
    ],
  },

  // ── STRATEGY ─────────────────────────────────────────────────────────────────
  {
    id: 'S1',
    perspective: 'strategy',
    capability: 'Operational Translation',
    type: 'anchor',
    weight: 20,
    text: 'Point to a workflow or operating procedure that was changed specifically because of a strategic AI priority.',
    options: [
      { value: 0, label: 'None can be identified' },
      { value: 1, label: 'Informal awareness' },
      { value: 2, label: 'One or two informal examples' },
      { value: 3, label: 'Some workflows formally updated' },
      { value: 4, label: 'Systematic translation across enterprise' },
      { value: 5, label: 'Strategy and operations co-evolve' },
    ],
  },
  {
    id: 'S2',
    perspective: 'strategy',
    capability: 'Portfolio Prioritization',
    type: 'anchor',
    weight: 18,
    text: 'What criteria determined which AI investments were funded versus not funded in the last planning cycle?',
    options: [
      { value: 0, label: 'No criteria — funded everything proposed' },
      { value: 1, label: 'Novelty or vendor pressure' },
      { value: 2, label: 'Informal judgment' },
      { value: 3, label: 'Some explicit criteria used' },
      { value: 4, label: 'Formal portfolio process with documented criteria' },
      { value: 5, label: 'Continuously measured and refined' },
    ],
  },
  {
    id: 'S3',
    perspective: 'strategy',
    capability: 'Human-Direction System',
    type: 'core',
    weight: 15,
    text: 'Can leadership describe, with the same precision they use for what the AI is trusted to do, who is still expected to exercise judgment and when — or does the strategy only describe the AI side?',
    options: [
      { value: 0, label: 'Only the AI side has ever been described' },
      { value: 1, label: 'Assumed, not stated' },
      { value: 2, label: 'Described for a few decisions' },
      { value: 3, label: 'Described for most high-stakes decisions' },
      { value: 4, label: 'Documented and reviewed for all major decisions' },
      { value: 5, label: 'Continuously tested and adjusted as AI capability expands' },
    ],
  },
  {
    id: 'S4',
    perspective: 'strategy',
    capability: 'Strategic Vision Alignment',
    type: 'core',
    weight: 13,
    text: 'Can employees name a business objective their AI work supports and how it is measured?',
    options: [
      { value: 0, label: 'No one can connect AI to business goals' },
      { value: 1, label: 'Leadership can but employees cannot' },
      { value: 2, label: 'Some teams can' },
      { value: 3, label: 'Most teams can' },
      { value: 4, label: 'Enterprise-wide alignment verified' },
      { value: 5, label: 'Continuously re-evaluated' },
    ],
  },
  {
    id: 'S5',
    perspective: 'strategy',
    capability: 'Adaptive Strategic Learning',
    type: 'core',
    weight: 12,
    text: 'What strategic assumption about AI has changed in the last 18 months based on operational evidence?',
    options: [
      { value: 0, label: 'Nothing has changed' },
      { value: 1, label: 'Aware strategy should adapt but no process' },
      { value: 2, label: 'One informal revision' },
      { value: 3, label: 'At least one documented revision with evidence' },
      { value: 4, label: 'Formal review process with documented revisions' },
      { value: 5, label: 'Structural learning drives continuous adaptation' },
    ],
  },
  {
    id: 'S6',
    perspective: 'strategy',
    capability: 'Value Realization',
    type: 'supporting',
    weight: 7,
    text: 'What operational outcome metric — not a usage metric — did the organization review for AI in the last 90 days?',
    options: [
      { value: 0, label: 'None — success is deployment' },
      { value: 1, label: 'Usage counts only' },
      { value: 2, label: 'Some qualitative outcomes' },
      { value: 3, label: 'One defined outcome metric' },
      { value: 4, label: 'Outcome framework reviewed regularly' },
      { value: 5, label: 'Value model drives portfolio decisions' },
    ],
  },

  // ── DATA ─────────────────────────────────────────────────────────────────────
  {
    id: 'D1',
    perspective: 'data',
    capability: 'Runtime Monitoring',
    type: 'anchor',
    weight: 21,
    text: 'Is the flow of data into your AI systems in everyday use actively watched in real time? Show an example of an alert it caught in the last 30 days.',
    options: [
      { value: 0, label: 'No monitoring' },
      { value: 1, label: 'Only periodic reports, not real time' },
      { value: 2, label: 'Some monitoring, but inconsistent' },
      { value: 3, label: 'Real-time monitoring on select systems' },
      { value: 4, label: 'Every system in everyday use is monitored, with alerts sent to the right people' },
      { value: 5, label: 'Monitoring predicts problems and can automatically shut things down before harm happens' },
    ],
  },
  {
    id: 'D2',
    perspective: 'data',
    capability: 'Data Lineage & Traceability',
    type: 'anchor',
    weight: 18,
    text: 'Can you trace the data used in a recent AI-supported decision from its source to the model output without manual reconstruction?',
    options: [
      { value: 0, label: 'Cannot be traced' },
      { value: 1, label: 'Source known but path unclear' },
      { value: 2, label: 'Partial lineage for some systems' },
      { value: 3, label: 'Full lineage for at least two systems' },
      { value: 4, label: 'Enterprise lineage standard, all production' },
      { value: 5, label: 'Real-time automated lineage' },
    ],
  },
  {
    id: 'D3',
    perspective: 'data',
    capability: 'Representational Stability',
    type: 'core',
    weight: 15,
    text: 'When did your organization last refresh the information your most important AI system learned from, and what caused that refresh to happen?',
    options: [
      { value: 0, label: 'Never updated, or we do not know' },
      { value: 1, label: 'Updated only when something visibly goes wrong' },
      { value: 2, label: 'Updated on a regular schedule' },
      { value: 3, label: 'Updated at least once because we noticed its accuracy slipping over time' },
      { value: 4, label: 'Automatically flagged and updated when accuracy starts slipping' },
      { value: 5, label: 'Continuously monitored to catch accuracy loss before it becomes visible' },
    ],
  },
  {
    id: 'D4',
    perspective: 'data',
    capability: 'Feedback Loop Detection',
    type: 'core',
    weight: 13,
    text: 'If AI-written content quietly worked its way into the data your organization treats as authoritative — the records or datasets other decisions get built on — would anyone know?',
    options: [
      { value: 0, label: 'We have not considered this a risk' },
      { value: 1, label: 'We know it is a risk but do not check for it' },
      { value: 2, label: 'We manually check our most important datasets' },
      { value: 3, label: 'AI-generated content is labeled as such in some systems' },
      { value: 4, label: 'AI-generated content is labeled and automatically tracked everywhere' },
      { value: 5, label: 'This is monitored in real time and caught before it spreads' },
    ],
  },
  {
    id: 'D5',
    perspective: 'data',
    capability: 'Runtime Data Trust',
    type: 'core',
    weight: 10,
    text: 'How does a decision-maker know, at the moment of decision, whether the data feeding an AI recommendation is reliable enough to act on?',
    options: [
      { value: 0, label: 'They trust the system' },
      { value: 1, label: 'They use general judgment' },
      { value: 2, label: 'Informal checks for some decisions' },
      { value: 3, label: 'Defined thresholds for at least one use case' },
      { value: 4, label: 'Enterprise data trust indicators at decision time' },
      { value: 5, label: 'Real-time decision-specific trust signals' },
    ],
  },
  {
    id: 'D6',
    perspective: 'data',
    capability: 'Security and Ethics',
    type: 'supporting',
    weight: 8,
    text: 'Who is allowed to access the raw training data behind your AI systems, and when was that access list last reviewed?',
    options: [
      { value: 0, label: 'Unknown — access has never been reviewed' },
      { value: 1, label: 'Some awareness, no formal list' },
      { value: 2, label: 'A list exists but is out of date' },
      { value: 3, label: 'Reviewed once, at launch' },
      { value: 4, label: 'Reviewed on a regular schedule' },
      { value: 5, label: 'Continuously monitored and enforced' },
    ],
  },

  // ── PEOPLE ────────────────────────────────────────────────────────────────────
  {
    id: 'P1',
    perspective: 'people',
    capability: 'Human Judgment Calibration',
    type: 'anchor',
    weight: 22,
    text: 'Give an example of a recent situation where an employee identified an AI recommendation as unreliable before acting on it. What did they notice and what happened?',
    options: [
      { value: 0, label: 'No examples exist' },
      { value: 1, label: 'Examples exist but were not acted on' },
      { value: 2, label: 'Occasional informal examples' },
      { value: 3, label: 'Some employees demonstrate calibrated judgment' },
      { value: 4, label: 'Defined verification expectations, assessed' },
      { value: 5, label: 'Continuously updated calibration' },
    ],
  },
  {
    id: 'P2',
    perspective: 'people',
    capability: 'Escalation & Accountability',
    type: 'anchor',
    weight: 20,
    text: 'When an employee encounters an AI output they are uncertain about, walk through what actually happens — not what should happen.',
    options: [
      { value: 0, label: 'They proceed anyway' },
      { value: 1, label: 'Depends on the individual' },
      { value: 2, label: 'Some escalate informally' },
      { value: 3, label: 'Defined path exists for some situations' },
      { value: 4, label: 'Standard escalation process, SLA measured' },
      { value: 5, label: 'Practiced, reliable, adaptive' },
    ],
  },
  {
    id: 'P3',
    perspective: 'people',
    capability: 'Psychological Safety & Learning Culture',
    type: 'core',
    weight: 16,
    text: 'Describe the last time an employee reported an AI output that turned out to be wrong or harmful. What happened to that employee?',
    options: [
      { value: 0, label: 'No reports exist' },
      { value: 1, label: 'Reports exist but consequences followed' },
      { value: 2, label: 'Neutral reception but no learning' },
      { value: 3, label: 'Open reception, some learning' },
      { value: 4, label: 'Systematic near-miss reporting and review' },
      { value: 5, label: 'Cultural norm, structural learning' },
    ],
  },
  {
    id: 'P4',
    perspective: 'people',
    capability: 'Human Oversight Behavior',
    type: 'core',
    weight: 14,
    text: 'Show an override record. Walk through what the reviewer saw, the authority they used, and the outcome.',
    options: [
      { value: 0, label: 'No override records exist' },
      { value: 1, label: 'Overrides happen informally' },
      { value: 2, label: 'Some overrides documented' },
      { value: 3, label: 'Override authority defined, records kept' },
      { value: 4, label: 'Oversight quality measured' },
      { value: 5, label: 'Continuously calibrated human-AI decision quality' },
    ],
  },
  {
    id: 'P5',
    perspective: 'people',
    capability: 'Operational Culture',
    type: 'core',
    weight: 11,
    text: 'What happens to an employee who slows a process down to verify an AI recommendation that turns out to be correct?',
    options: [
      { value: 0, label: 'Seen as slowing things down' },
      { value: 1, label: 'Tolerated but not valued' },
      { value: 2, label: 'Neutral reception' },
      { value: 3, label: 'Informally valued' },
      { value: 4, label: 'Formally recognized and reinforced' },
      { value: 5, label: 'Self-reinforcing cultural norm' },
    ],
  },
  {
    id: 'P6',
    perspective: 'people',
    capability: 'Behavioral Measurement',
    type: 'supporting',
    weight: 7,
    text: "For your highest-stakes AI-supported decisions, how often do people override or reject the AI's recommendation — and what has that told you?",
    options: [
      { value: 0, label: 'Unknown — we do not track this' },
      { value: 1, label: 'Tracked informally, not with real numbers' },
      { value: 2, label: 'Measured for one specific decision process' },
      { value: 3, label: 'Measured for all our key decision processes' },
      { value: 4, label: 'Measured consistently across the organization, with a formal framework' },
      { value: 5, label: 'These measurements actively drive ongoing improvements' },
    ],
  },

  // ── TECHNOLOGY ────────────────────────────────────────────────────────────────
  {
    id: 'T1',
    perspective: 'technology',
    capability: 'Operational Observability',
    type: 'anchor',
    weight: 22,
    text: 'Show the monitoring dashboard for a production AI system and point to the last alert it generated and what happened.',
    options: [
      { value: 0, label: 'No monitoring exists' },
      { value: 1, label: 'Manual checks only' },
      { value: 2, label: 'Some monitoring, inconsistent alerts' },
      { value: 3, label: 'Monitoring with alerts on selected systems' },
      { value: 4, label: 'All production systems monitored, drift detection' },
      { value: 5, label: 'Predictive degradation signals, automated circuit breakers' },
    ],
  },
  {
    id: 'T2',
    perspective: 'technology',
    capability: 'Model Operations',
    type: 'anchor',
    weight: 18,
    text: 'Walk through the last time an AI system was updated or replaced: how was it tested before going live, who signed off, and what was the plan if something went wrong?',
    options: [
      { value: 0, label: 'No process — it was just switched on' },
      { value: 1, label: 'Tested informally, no real process' },
      { value: 2, label: 'Some steps are documented' },
      { value: 3, label: 'A repeatable process exists for at least one AI system' },
      { value: 4, label: 'A standard process is required for every AI system' },
      { value: 5, label: 'Testing and rollout are automated and continuously managed' },
    ],
  },
  {
    id: 'T3',
    perspective: 'technology',
    capability: 'Runtime Governance Support',
    type: 'core',
    weight: 15,
    text: "Using only the records the system itself kept — not anyone's memory or explanation — could you reconstruct exactly how a recent AI-supported decision was reached?",
    options: [
      { value: 0, label: 'No — it cannot be reconstructed from records alone' },
      { value: 1, label: 'Partial records exist, with gaps' },
      { value: 2, label: 'Some systems keep records of their decisions' },
      { value: 3, label: 'At least two systems keep records detailed enough to stand up to scrutiny' },
      { value: 4, label: 'Every system in everyday use keeps a full record' },
      { value: 5, label: 'Complete, real-time records are available for every decision' },
    ],
  },
  {
    id: 'T4',
    perspective: 'technology',
    capability: 'Reliability Engineering',
    type: 'core',
    weight: 13,
    text: "Describe what happens when an AI system in everyday use is fed bad, unusual, or unexpected input. Is there a defined, safe way it's supposed to respond?",
    options: [
      { value: 0, label: 'Unknown — we have not defined this' },
      { value: 1, label: 'It fails or produces errors with no defined response' },
      { value: 2, label: 'Handled informally, case by case' },
      { value: 3, label: 'At least one system has a defined safe response' },
      { value: 4, label: 'Every AI system is required to have a defined safe response' },
      { value: 5, label: 'Systems detect problems in advance and adjust automatically' },
    ],
  },
  {
    id: 'T5',
    perspective: 'technology',
    capability: 'Vendor & Dependency Management',
    type: 'supporting',
    weight: 8,
    text: 'If the outside AI service your organization depends on changed how it behaves overnight — without warning — what would actually happen?',
    options: [
      { value: 0, label: 'We would find out when something breaks' },
      { value: 1, label: 'We would notice eventually' },
      { value: 2, label: 'We would detect it within a few days' },
      { value: 3, label: 'We have a defined response process' },
      { value: 4, label: 'We watch for behavior changes and have a backup plan' },
      { value: 5, label: 'We use multiple providers so we are not dependent on just one' },
    ],
  },
  {
    id: 'T6',
    perspective: 'technology',
    capability: 'Security',
    type: 'supporting',
    weight: 6,
    text: 'Who last audited the access controls on your AI training and deployment pipeline, and when?',
    options: [
      { value: 0, label: "Unknown — 'I'd have to check'" },
      { value: 1, label: 'Never formally audited' },
      { value: 2, label: 'Audited once, at launch' },
      { value: 3, label: 'Audited for at least one system, on a defined schedule' },
      { value: 4, label: 'Audited for all production systems, on a defined schedule' },
      { value: 5, label: 'Continuously monitored with automated alerts on change' },
    ],
  },
]

export const PERSPECTIVE_ORDER: Perspective[] = [
  'governance',
  'strategy',
  'data',
  'people',
  'technology',
]

export const PERSPECTIVE_META: Record<
  Perspective,
  { label: string; description: string; color: string; borderColor: string; bgColor: string }
> = {
  governance: {
    label: 'Governance',
    description: 'Accountability, escalation, oversight, and runtime controls for AI-supported decisions.',
    color: 'text-blue-600',
    borderColor: 'border-blue-500',
    bgColor: 'bg-blue-50',
  },
  strategy: {
    label: 'Strategy',
    description: 'How AI priorities translate into operations, portfolio decisions, and measurable outcomes.',
    color: 'text-violet-600',
    borderColor: 'border-violet-500',
    bgColor: 'bg-violet-50',
  },
  data: {
    label: 'Data',
    description: 'Runtime data integrity, lineage, monitoring, and trust at the moment of decision.',
    color: 'text-cyan-600',
    borderColor: 'border-cyan-500',
    bgColor: 'bg-cyan-50',
  },
  people: {
    label: 'People',
    description: 'Human judgment calibration, escalation behavior, oversight culture, and measurement.',
    color: 'text-amber-600',
    borderColor: 'border-amber-500',
    bgColor: 'bg-amber-50',
  },
  technology: {
    label: 'Technology',
    description: 'Observability, model operations, governance tooling, reliability, and prompt management.',
    color: 'text-emerald-600',
    borderColor: 'border-emerald-500',
    bgColor: 'bg-emerald-50',
  },
}
