import type { Domain, Question } from './types'

export const QUESTIONS: Question[] = [
  // ── GOVERNANCE ──────────────────────────────────────────────────────────────
  {
    id: 'G1',
    domain: 'governance',
    capability: 'Accountability Architecture',
    type: 'anchor',
    weight: 22,
    text: 'Are accountable owners named for AI-supported decisions, and can they be reached when a decision is contested?',
    options: [
      { value: 0, label: 'None' },
      { value: 1, label: 'Informal only' },
      { value: 2, label: 'Some decisions' },
      { value: 3, label: 'Most decisions' },
      { value: 4, label: 'All major decisions, formally assigned' },
      { value: 5, label: 'Continuously measured and enforced' },
    ],
  },
  {
    id: 'G2',
    domain: 'governance',
    capability: 'Escalation & Exception Handling',
    type: 'anchor',
    weight: 18,
    text: 'When an AI output is disputed or uncertain, what happens operationally? Walk through the last example.',
    options: [
      { value: 0, label: 'No process exists' },
      { value: 1, label: 'Depends on who notices' },
      { value: 2, label: 'Informal escalation sometimes' },
      { value: 3, label: 'Defined path exists, used inconsistently' },
      { value: 4, label: 'Standard process, measured' },
      { value: 5, label: 'Adaptive and continuously improved' },
    ],
  },
  {
    id: 'G3',
    domain: 'governance',
    capability: 'Human Oversight & Intervention',
    type: 'core',
    weight: 15,
    text: 'Can human reviewers override or pause an AI-supported decision? Show the last time this happened.',
    options: [
      { value: 0, label: 'No override capability' },
      { value: 1, label: 'In principle but no examples' },
      { value: 2, label: 'Occasionally, informally' },
      { value: 3, label: 'Defined authority, used in some workflows' },
      { value: 4, label: 'Formal authority, measured' },
      { value: 5, label: 'Continuously calibrated' },
    ],
  },
  {
    id: 'G4',
    domain: 'governance',
    capability: 'Runtime Governance & Monitoring',
    type: 'core',
    weight: 14,
    text: 'Does governance monitoring continue after AI systems are deployed? What signals reach governance owners from production?',
    options: [
      { value: 0, label: 'Governance ends at deployment' },
      { value: 1, label: 'Ad hoc monitoring' },
      { value: 2, label: 'Some production signals' },
      { value: 3, label: 'Selected systems monitored' },
      { value: 4, label: 'All production systems, standardized' },
      { value: 5, label: 'Adaptive, predictive' },
    ],
  },
  {
    id: 'G5',
    domain: 'governance',
    capability: 'Risk Classification & Control',
    type: 'core',
    weight: 12,
    text: 'Are AI use cases classified by risk level, and do higher-risk cases receive more intensive controls?',
    options: [
      { value: 0, label: 'All treated the same' },
      { value: 1, label: 'Informal risk awareness' },
      { value: 2, label: 'Some cases risk-ranked' },
      { value: 3, label: 'Local risk tiers exist' },
      { value: 4, label: 'Enterprise risk classification standard' },
      { value: 5, label: 'Continuously refined' },
    ],
  },
  {
    id: 'G6',
    domain: 'governance',
    capability: 'Incident & Failure Response',
    type: 'supporting',
    weight: 8,
    text: 'Describe the last AI-related incident: how it was detected, who was notified, what changed as a result.',
    options: [
      { value: 0, label: 'No incidents recognized' },
      { value: 1, label: 'Incidents handled informally' },
      { value: 2, label: 'Some incidents documented' },
      { value: 3, label: 'Classification and escalation process' },
      { value: 4, label: 'Standard process, measured' },
      { value: 5, label: 'Incidents drive systemic improvement' },
    ],
  },

  // ── STRATEGY ─────────────────────────────────────────────────────────────────
  {
    id: 'S1',
    domain: 'strategy',
    capability: 'Operational Translation',
    type: 'anchor',
    weight: 20,
    text: 'Point to a workflow or operating procedure that was changed specifically because of a strategic AI priority.',
    options: [
      { value: 0, label: 'None can be identified' },
      { value: 1, label: 'Informal awareness' },
      { value: 2, label: 'One or two informal examples' },
      { value: 3, label: 'Some workflows formally updated' },
      { value: 4, label: 'Systematic translation across enterprise' },
      { value: 5, label: 'Strategy and operations co-evolve' },
    ],
  },
  {
    id: 'S2',
    domain: 'strategy',
    capability: 'Portfolio Prioritization',
    type: 'anchor',
    weight: 18,
    text: 'What criteria determined which AI investments were funded versus not funded in the last planning cycle?',
    options: [
      { value: 0, label: 'No criteria — funded everything proposed' },
      { value: 1, label: 'Novelty or vendor pressure' },
      { value: 2, label: 'Informal judgment' },
      { value: 3, label: 'Some explicit criteria used' },
      { value: 4, label: 'Formal portfolio process with documented criteria' },
      { value: 5, label: 'Continuously measured and refined' },
    ],
  },
  {
    id: 'S3',
    domain: 'strategy',
    capability: 'Cross-Functional Coordination',
    type: 'core',
    weight: 15,
    text: 'When two functions pursue conflicting AI directions, how is it resolved?',
    options: [
      { value: 0, label: 'Stronger function wins' },
      { value: 1, label: 'Informal negotiation' },
      { value: 2, label: 'Occasional cross-functional discussion' },
      { value: 3, label: 'Some coordination forums exist' },
      { value: 4, label: 'Defined coordination structure with decision rights' },
      { value: 5, label: 'Adaptive coordination across ecosystem' },
    ],
  },
  {
    id: 'S4',
    domain: 'strategy',
    capability: 'Strategic Vision Alignment',
    type: 'core',
    weight: 13,
    text: 'Can employees name a business objective their AI work supports and how it is measured?',
    options: [
      { value: 0, label: 'No one can connect AI to business goals' },
      { value: 1, label: 'Leadership can but employees cannot' },
      { value: 2, label: 'Some teams can' },
      { value: 3, label: 'Most teams can' },
      { value: 4, label: 'Enterprise-wide alignment verified' },
      { value: 5, label: 'Continuously re-evaluated' },
    ],
  },
  {
    id: 'S5',
    domain: 'strategy',
    capability: 'Adaptive Strategic Learning',
    type: 'core',
    weight: 12,
    text: 'What strategic assumption about AI has changed in the last 18 months based on operational evidence?',
    options: [
      { value: 0, label: 'Nothing has changed' },
      { value: 1, label: 'Aware strategy should adapt but no process' },
      { value: 2, label: 'One informal revision' },
      { value: 3, label: 'At least one documented revision with evidence' },
      { value: 4, label: 'Formal review process with documented revisions' },
      { value: 5, label: 'Structural learning drives continuous adaptation' },
    ],
  },
  {
    id: 'S6',
    domain: 'strategy',
    capability: 'Value Realization',
    type: 'supporting',
    weight: 7,
    text: 'What operational outcome metric — not a usage metric — did the organization review for AI in the last 90 days?',
    options: [
      { value: 0, label: 'None — success is deployment' },
      { value: 1, label: 'Usage counts only' },
      { value: 2, label: 'Some qualitative outcomes' },
      { value: 3, label: 'One defined outcome metric' },
      { value: 4, label: 'Outcome framework reviewed regularly' },
      { value: 5, label: 'Value model drives portfolio decisions' },
    ],
  },

  // ── DATA ─────────────────────────────────────────────────────────────────────
  {
    id: 'D1',
    domain: 'data',
    capability: 'Runtime Monitoring',
    type: 'anchor',
    weight: 21,
    text: 'Does the organization have live telemetry monitoring the data pipelines feeding production AI systems? Show an example alert from the last 30 days.',
    options: [
      { value: 0, label: 'No monitoring' },
      { value: 1, label: 'Periodic batch reports' },
      { value: 2, label: 'Some monitoring, inconsistent' },
      { value: 3, label: 'Monitoring on selected systems' },
      { value: 4, label: 'All production systems monitored, alerts routed' },
      { value: 5, label: 'Predictive, automated circuit breakers' },
    ],
  },
  {
    id: 'D2',
    domain: 'data',
    capability: 'Data Lineage & Traceability',
    type: 'anchor',
    weight: 18,
    text: 'Can you trace the data used in a recent AI-supported decision from its source to the model output without manual reconstruction?',
    options: [
      { value: 0, label: 'Cannot be traced' },
      { value: 1, label: 'Source known but path unclear' },
      { value: 2, label: 'Partial lineage for some systems' },
      { value: 3, label: 'Full lineage for at least two systems' },
      { value: 4, label: 'Enterprise lineage standard, all production' },
      { value: 5, label: 'Real-time automated lineage' },
    ],
  },
  {
    id: 'D3',
    domain: 'data',
    capability: 'Representational Stability',
    type: 'core',
    weight: 15,
    text: 'When did the organization last update training data for its most critical AI system, and what triggered the update?',
    options: [
      { value: 0, label: 'Never updated or unknown' },
      { value: 1, label: 'Updated ad hoc when problems emerge' },
      { value: 2, label: 'Periodic updates on schedule' },
      { value: 3, label: 'At least one drift-triggered update' },
      { value: 4, label: 'Automated drift detection triggers updates' },
      { value: 5, label: 'Predictive stability monitoring' },
    ],
  },
  {
    id: 'D4',
    domain: 'data',
    capability: 'Feedback Loop Detection',
    type: 'core',
    weight: 13,
    text: 'Does the organization track whether AI-generated content has entered operational or training data streams?',
    options: [
      { value: 0, label: 'Not aware this is a risk' },
      { value: 1, label: 'Aware but no monitoring' },
      { value: 2, label: 'Manual checks on critical datasets' },
      { value: 3, label: 'Tagged AI-generated content in selected systems' },
      { value: 4, label: 'Enterprise tagging standard, automated monitoring' },
      { value: 5, label: 'Real-time contamination monitoring with circuit breakers' },
    ],
  },
  {
    id: 'D5',
    domain: 'data',
    capability: 'Runtime Data Trust',
    type: 'core',
    weight: 10,
    text: 'How does a decision-maker know, at the moment of decision, whether the data feeding an AI recommendation is reliable enough to act on?',
    options: [
      { value: 0, label: 'They trust the system' },
      { value: 1, label: 'They use general judgment' },
      { value: 2, label: 'Informal checks for some decisions' },
      { value: 3, label: 'Defined thresholds for at least one use case' },
      { value: 4, label: 'Enterprise data trust indicators at decision time' },
      { value: 5, label: 'Real-time decision-specific trust signals' },
    ],
  },
  {
    id: 'D6',
    domain: 'data',
    capability: 'Operational Data Escalation',
    type: 'supporting',
    weight: 8,
    text: 'Walk through the last data escalation: what triggered it, who received it, how long it took, and what was decided.',
    options: [
      { value: 0, label: 'No escalation has occurred or no process' },
      { value: 1, label: 'Ad hoc, depends on individual' },
      { value: 2, label: 'Informal escalation occasionally' },
      { value: 3, label: 'Defined path, used inconsistently' },
      { value: 4, label: 'Standard protocol, SLA measured' },
      { value: 5, label: 'Near-automated for threshold violations' },
    ],
  },

  // ── PEOPLE ────────────────────────────────────────────────────────────────────
  {
    id: 'P1',
    domain: 'people',
    capability: 'Human Judgment Calibration',
    type: 'anchor',
    weight: 22,
    text: 'Give an example of a recent situation where an employee identified an AI recommendation as unreliable before acting on it. What did they notice and what happened?',
    options: [
      { value: 0, label: 'No examples exist' },
      { value: 1, label: 'Examples exist but were not acted on' },
      { value: 2, label: 'Occasional informal examples' },
      { value: 3, label: 'Some employees demonstrate calibrated judgment' },
      { value: 4, label: 'Defined verification expectations, assessed' },
      { value: 5, label: 'Continuously updated calibration' },
    ],
  },
  {
    id: 'P2',
    domain: 'people',
    capability: 'Escalation & Accountability',
    type: 'anchor',
    weight: 20,
    text: 'When an employee encounters an AI output they are uncertain about, walk through what actually happens — not what should happen.',
    options: [
      { value: 0, label: 'They proceed anyway' },
      { value: 1, label: 'Depends on the individual' },
      { value: 2, label: 'Some escalate informally' },
      { value: 3, label: 'Defined path exists for some situations' },
      { value: 4, label: 'Standard escalation process, SLA measured' },
      { value: 5, label: 'Practiced, reliable, adaptive' },
    ],
  },
  {
    id: 'P3',
    domain: 'people',
    capability: 'Psychological Safety & Learning Culture',
    type: 'core',
    weight: 16,
    text: 'Describe the last time an employee reported an AI output that turned out to be wrong or harmful. What happened to that employee?',
    options: [
      { value: 0, label: 'No reports exist' },
      { value: 1, label: 'Reports exist but consequences followed' },
      { value: 2, label: 'Neutral reception but no learning' },
      { value: 3, label: 'Open reception, some learning' },
      { value: 4, label: 'Systematic near-miss reporting and review' },
      { value: 5, label: 'Cultural norm, structural learning' },
    ],
  },
  {
    id: 'P4',
    domain: 'people',
    capability: 'Human Oversight Behavior',
    type: 'core',
    weight: 14,
    text: 'Show an override record. Walk through what the reviewer saw, the authority they used, and the outcome.',
    options: [
      { value: 0, label: 'No override records exist' },
      { value: 1, label: 'Overrides happen informally' },
      { value: 2, label: 'Some overrides documented' },
      { value: 3, label: 'Override authority defined, records kept' },
      { value: 4, label: 'Oversight quality measured' },
      { value: 5, label: 'Continuously calibrated human-AI decision quality' },
    ],
  },
  {
    id: 'P5',
    domain: 'people',
    capability: 'Operational Culture',
    type: 'core',
    weight: 11,
    text: 'What happens to an employee who slows a process down to verify an AI recommendation that turns out to be correct?',
    options: [
      { value: 0, label: 'Seen as slowing things down' },
      { value: 1, label: 'Tolerated but not valued' },
      { value: 2, label: 'Neutral reception' },
      { value: 3, label: 'Informally valued' },
      { value: 4, label: 'Formally recognized and reinforced' },
      { value: 5, label: 'Self-reinforcing cultural norm' },
    ],
  },
  {
    id: 'P6',
    domain: 'people',
    capability: 'Behavioral Measurement',
    type: 'supporting',
    weight: 7,
    text: 'What is the override rate for your highest-stakes AI-supported decision workflow, and what has it told you?',
    options: [
      { value: 0, label: 'Unknown and unmeasured' },
      { value: 1, label: 'Tracked informally' },
      { value: 2, label: 'Measured for one workflow' },
      { value: 3, label: 'Measured for key workflows' },
      { value: 4, label: 'Enterprise behavioral measurement framework' },
      { value: 5, label: 'Metrics drive continuous improvement' },
    ],
  },

  // ── TECHNOLOGY ────────────────────────────────────────────────────────────────
  {
    id: 'T1',
    domain: 'technology',
    capability: 'Operational Observability',
    type: 'anchor',
    weight: 22,
    text: 'Show the monitoring dashboard for a production AI system and point to the last alert it generated and what happened.',
    options: [
      { value: 0, label: 'No monitoring exists' },
      { value: 1, label: 'Manual checks only' },
      { value: 2, label: 'Some monitoring, inconsistent alerts' },
      { value: 3, label: 'Monitoring with alerts on selected systems' },
      { value: 4, label: 'All production systems monitored, drift detection' },
      { value: 5, label: 'Predictive degradation signals, automated circuit breakers' },
    ],
  },
  {
    id: 'T2',
    domain: 'technology',
    capability: 'Model Operations',
    type: 'anchor',
    weight: 18,
    text: 'Walk through the last model update: deployment process, validation steps, who approved it, and what the rollback plan was.',
    options: [
      { value: 0, label: 'No process — pushed to production' },
      { value: 1, label: 'Informal testing' },
      { value: 2, label: 'Some documentation' },
      { value: 3, label: 'Repeatable process for at least one model' },
      { value: 4, label: 'Enterprise standard for all models' },
      { value: 5, label: 'Automated validation, continuous lifecycle management' },
    ],
  },
  {
    id: 'T3',
    domain: 'technology',
    capability: 'Runtime Governance Support',
    type: 'core',
    weight: 15,
    text: 'Reconstruct the decision path for a recent AI-supported action using system-generated records alone — no human narration.',
    options: [
      { value: 0, label: 'Cannot be done' },
      { value: 1, label: 'Partial logs exist' },
      { value: 2, label: 'Some systems log decisions' },
      { value: 3, label: 'At least two systems generate governance-quality records' },
      { value: 4, label: 'All production systems generate audit trails' },
      { value: 5, label: 'Real-time comprehensive governance evidence' },
    ],
  },
  {
    id: 'T4',
    domain: 'technology',
    capability: 'Reliability Engineering',
    type: 'core',
    weight: 13,
    text: 'Describe what happens operationally when a production AI system receives degraded or anomalous inputs. What is the defined fallback behavior?',
    options: [
      { value: 0, label: 'Unknown — we have not defined this' },
      { value: 1, label: 'System fails or produces errors' },
      { value: 2, label: 'Some informal handling' },
      { value: 3, label: 'At least one system has defined degradation behavior' },
      { value: 4, label: 'Enterprise reliability standard, all systems' },
      { value: 5, label: 'Predictive failure detection, adaptive resilience' },
    ],
  },
  {
    id: 'T5',
    domain: 'technology',
    capability: 'Vendor & Dependency Management',
    type: 'supporting',
    weight: 8,
    text: 'What happens operationally if your primary LLM API provider changes model behavior without advance notice?',
    options: [
      { value: 0, label: 'We would find out when something breaks' },
      { value: 1, label: 'We would notice eventually' },
      { value: 2, label: 'We would detect in days' },
      { value: 3, label: 'We have a defined response process' },
      { value: 4, label: 'We monitor for behavioral changes, contingency plans' },
      { value: 5, label: 'Multi-vendor resilience, continuous monitoring' },
    ],
  },
  {
    id: 'T6',
    domain: 'technology',
    capability: 'Prompt Governance',
    type: 'supporting',
    weight: 6,
    text: 'If the person who wrote your primary operational prompts left today, what happens to operational continuity?',
    options: [
      { value: 0, label: 'Significant disruption — prompts are personal' },
      { value: 1, label: 'Partial disruption' },
      { value: 2, label: 'Some prompts documented' },
      { value: 3, label: 'Critical prompts version-controlled and documented' },
      { value: 4, label: 'Enterprise prompt governance standard' },
      { value: 5, label: 'Prompts governed as operational specifications' },
    ],
  },
]

export const DOMAIN_ORDER: Domain[] = [
  'governance',
  'strategy',
  'data',
  'people',
  'technology',
]

export const DOMAIN_META: Record<
  Domain,
  { label: string; description: string; color: string; borderColor: string; bgColor: string }
> = {
  governance: {
    label: 'Governance',
    description: 'Accountability, escalation, oversight, and runtime controls for AI-supported decisions.',
    color: 'text-blue-600',
    borderColor: 'border-blue-500',
    bgColor: 'bg-blue-50',
  },
  strategy: {
    label: 'Strategy',
    description: 'How AI priorities translate into operations, portfolio decisions, and measurable outcomes.',
    color: 'text-violet-600',
    borderColor: 'border-violet-500',
    bgColor: 'bg-violet-50',
  },
  data: {
    label: 'Data',
    description: 'Runtime data integrity, lineage, monitoring, and trust at the moment of decision.',
    color: 'text-cyan-600',
    borderColor: 'border-cyan-500',
    bgColor: 'bg-cyan-50',
  },
  people: {
    label: 'People',
    description: 'Human judgment calibration, escalation behavior, oversight culture, and measurement.',
    color: 'text-amber-600',
    borderColor: 'border-amber-500',
    bgColor: 'bg-amber-50',
  },
  technology: {
    label: 'Technology',
    description: 'Observability, model operations, governance tooling, reliability, and prompt management.',
    color: 'text-emerald-600',
    borderColor: 'border-emerald-500',
    bgColor: 'bg-emerald-50',
  },
}
